### ISSUE TITLE
CUDA out of memory when update label on JSRT dataset

### ISSUE THREAD

**Issue by shikangjian** [gaozhitong/SP_guided_Noisy_Label_Seg#4]
[20:35:49.122] update_label
[20:35:49.122] E step into: generated new pseudo for lung_a3b5_spemj01.
Warming up E_train_loader
Num per E_train_loader 1
  5%|███▌                                                                   | 10/201 [12:36<4:00:53, 75.67s/it]
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    nlss_seg.noise_aware_training()
  File "/home/skj/python_work/Mine_Noisy_Label_Seg/lib/nlss.py", line 444, in noise_aware_training
    self.label_refinement(first_tag=first_E_tag)
  File "/home/skj/python_work/Mine_Noisy_Label_Seg/lib/nlss.py", line 920, in label_refinement
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/skj/python_work/Mine_Noisy_Label_Seg/lib/models/nnU_net.py", line 402, in forward
    x = self.conv_blocks_localization[u](x)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/skj/python_work/Mine_Noisy_Label_Seg/lib/models/nnU_net.py", line 139, in forward
    return self.blocks(x)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/skj/python_work/Mine_Noisy_Label_Seg/lib/models/nnU_net.py", line 65, in forward
    return self.lrelu(self.instnorm(x))
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/skj/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 400.00 MiB (GPU 1; 10.76 GiB total capacity; 2.65 GiB already allocated; 356.12 MiB free; 3.12 GiB reserved in total by PyTorch)

CUDA out of memory when updating label on JSRT dataset. I have resized the batch and used two GeForce RTX 2080 Ti.

**Comment by gaozhitong** [comment]
Please refer to [issue #3](https://github.com/gaozhitong/SP_guided_Noisy_Label_Seg/issues/3).
